### ISSUE TITLE
Stable Diffusion v2.1

### ISSUE THREAD

**Issue by greeneggsandyaml** [minimaxir/stable-diffusion-negative-prompt#1]
Hello, thanks for your work training these embeddings! 

Would it be possible for you to train embeddings for Stable Diffusion v2.1? The general consensus seems to be that these models are a lot better, so it would be great to have <midjourney> and <wrong> embeddings for these models just like v2.0.

Thanks again for your work!

**Comment by minimaxir** [comment]
The embeddings used here *should* work with SD 2.1 without any changes! (as noted in the article, the reason new embeddings were necessary is due to the text encoder change)
